apiVersion: v1
kind: Service
metadata:
  name: carisurau-service
spec:
  type: NodePort
  selector:
    app: carisurau
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  externalIPs:
  - 192.168.1.246
  
